name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-focal

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps chromium
          ls -la /ms-playwright/
          echo "Browser installation complete"
          npm ci

      - name: Build the app
        run: npm run build

      - name: Run Playwright tests
        run: |
          ls -la /ms-playwright/
          PLAYWRIGHT_DEBUG=1 npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
